language: r
sudo: false
dist: xenial
cache: packages

before_install: R -e 'source("https://install-github.me/r-lib/remotes")'

r_packages:
  - covr

jobs:
  include:
    - r: bioc-devel
      after_success:
      - Rscript -e 'covr::codecov()'
    - r: devel
    - r: release
env:
  global:
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
