language: r
sudo: false
dist: xenial
cache: packages

r_packages:
  - covr
  - testthat
  - Rcpp
  - rlang

bioc_packages:
  - BiocParallel

jobs:
  include:
    - r: bioc-devel
    - r: devel
      after_success:
      - Rscript -e 'covr::codecov()'
    - r: release
env:
  global:
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
